### ISSUE TITLE
User-Story-1 create card

### ISSUE THREAD

**Issue by JohannesMisch** [JohannesMisch/Capstone-project#1]
## Value Proposition

As a User 
I want to have a landing page   
so that I can see all the devices I want to track. 

## Description

![Image](https://user-images.githubusercontent.com/84077369/213486712-634f4926-3856-441f-bc95-351bb6f2beda.png)

## Acceptance Criteria
- [x] I want to display multiple cards with dummy data
  - [x] each card is going to display "Model" 
  - [x] each card is going to display  "Name" 
  - [x] each card is going to display "picture"
  - [x] each card is going to display "Power consumption on"
  - [x] each card is going to display "Power consumption Standby"
  - [x] each card is going to display "Location"

## Tasks

- [x] create dummy data in a Static JSON
   - [  ] db.json: 
 ```json
[
 {
    "id": 0,
    "device_category": "TV",
    "model": "LG 55NANO796PC LED TV",
    "power consumption": 95,
    "power consumption standby": 0.5,
    "average usage time": 4,
    "location": "Livingroom"
  }
]
```
- [x] create an unordered list
  - [x] inside the unordered list render as many list items as there are objects in the db.json(use .map)
  - [x] inside the list item create a  section
    - [x] inside the section create an unordered list  
    - [x] inside the unordered list create six list items 
       - [x] first list item displays "Device_category:" and the value of the key-value pair with the key: device_category
       - [x] second list item displays "Model:" and the value of the key-value pair with the key: model
       - [x] third list item displays "Power consumption:" and the value of the key-value pair with the key: power consumption
       - [x] fourth list item displays "Power consumption Standby:" and the value of the key-value pair with the key: power consumption standby
       - [x] fifth list item displays "Average usage time:" and the value of the key-value pair with the key: average usage time
       - [x] sixth list item displays "Location:" and the value of the key-value pair with the key: location

## Complexity

XL

**Comment by mbosselmann** [comment]
Hi Johannes,
we like your user story! 💪 But we have some remarks for you:

- In general we would prefer that you write your user story in English (@shebtastic is to blame here) :)

**Acceptance criteria**
- "Nutzungsdauer" and "Stromverbrauch" are for us not the same and therefore we do not see how an optional "Stromverbrauch" is displayed in you wireframe

**Tasks**
- You may add an example data structure if you have already thought about it (that is up to you)
- the name of your props should be in English
- and the props values should have examples for better understanding or be left out
- instead of working with a hidden p element, use conditional rendering
- also a p element may be not the right semantic choice :)

Aaaaaand: You may think about a descriptive title for this user story in addition to the user story number.

If you have questions, feel free to ask us! After editing your user story, please post the user story again in our thread. :)

**Comment by shebtastic** [comment]
Hi Johannes,

thanks for implementing the changes!

We have a few more minor adjustments:

**Acceptance Criteria**
- Right now the acceptance criterias presented give the impression that you're only creating a single card. Since your story is about creating a list of cards, you should also add a criteria for this and adjust the phrasing of the other criterias accordingly.
  > 💡 you can also nest checkboxed lists in markdown
  ```md
  - [ ] create `Card` Component
    - [ ] display model
  - [ ] ...
  ```

**Tasks**
- Your db.json has invalid syntax. Please update the the example. You could also wrap this in a markdown code block using:
  >  \```json
  > ...
  > \```
- You might want to add more Tasks as you go along, but we won't block approval because of this. 😁

If you have questions, feel free to ask us! After editing your user story, please post the user story again in our thread. :)

**Comment by F-Kirchhoff** [comment]
Hey Johannes,
you are almost ready to go! Can you please write whole sentences for the acceptance criteria (I know it sounds knitpicky, but it really helps you to get the most out of the capstone). You could write for example:
- displays a card component for each item in the db.json
- each card has a title
- each card displays a picture
- each card ...

In your tasks you could add more detail as well, but for now it is ok. But in the next user stories please add more steps how to are going to create the upcoming freatures.

**Comment by mbosselmann** [comment]
Hi Johannes,
you rock! 🪨 Your user story is now ready to go. The last note is only a formatting issue in your tasks: "[ ]db.json", BUT this does not hinder me in approving your user story!
Awesome work! 

Happy hacking! 🚀 :octocat: 🥳
