### ISSUE TITLE
Delete button

### ISSUE THREAD

**Issue by JohannesMisch** [JohannesMisch/Capstone-project#11]
## Value Proposition

As a user
I want to have a button 
so that I can delete devices

## Description

![Delete button](https://user-images.githubusercontent.com/84077369/215096573-8a90c669-a304-4767-847e-ebbf5914f487.png)

## Acceptance Criteria

- [ ] the delete button should always be displayed at the bottom of the page
- [ ] the button should delete the correct device

## Tasks

- [ ] create a button 
   - [ ] onClick the button should call a filter function 
   - [ ] the filter function should delete only one device with this specific id of this object 

## Complexity

S

**Comment by RobinWitt** [comment]
looks good to me!
