### ISSUE TITLE
helper list

### ISSUE THREAD

**Issue by JohannesMisch** [JohannesMisch/Capstone-project#12]
## Value Proposition

As a user
I want to have a list that is sorted, first all devices in the category Appliances second all devices in the category Entertainment and last all devices in the category Work.

## Description
![helper list](https://user-images.githubusercontent.com/84077369/215122528-210fcc58-a4a6-4075-9daa-0ee082ab9893.png)

## Acceptance Criteria

- [ ] display a sorted list of all the devices

## Tasks

- [ ] sort the array with all the device entries and sort it as mentioned above
- [ ] create a component that displays the sorted array in an unordered list

## Complexity

S
