### ISSUE TITLE
Chart.js 

### ISSUE THREAD

**Issue by JohannesMisch** [JohannesMisch/Capstone-project#15]
## Value Proposition

As a user
I want to have an overview in form of a chart
so that I can easily get an idea of how big of an impact each device category has on your overall electricity expense.

## Description

![chart js](https://user-images.githubusercontent.com/84077369/215329666-1915a07b-ae23-4649-8de1-e381fa169dd8.png)

## Acceptance Criteria

- [ ] Display a chart 
   - [ ] Inside this chart there should be a segment for each category of devices
   - [ ] Each category should be a portion of the overall electricity expense
- [ ] There needs to be an input field to enter the electricity price 

## Tasks

- [ ] npm i `chart.js `
- [ ] npm i `react-chartjs-2`
- [ ] Create a new component file for the chart
- [ ] Import a chart from `react-chartjs-2`
- [ ] Create the chart with `chart.js`
- [ ] Create an input field for a number input (electricity price) 
   - [ ] give the input field a pattern that allows only numbers as an input 
- [ ] Create a paragraph to display the overall electricity expense 

## Complexity

L

**Comment by ghost** [comment]
you have some formatting issues in the AC/T but the rest looks good to me :)
