### ISSUE TITLE
edit button

### ISSUE THREAD

**Issue by JohannesMisch** [JohannesMisch/Capstone-project#16]
## Value Proposition

As a user
I want to have an edit button  
so that I can change the Information on the devices I added.

## Description

![Edit Button](https://user-images.githubusercontent.com/84077369/215337282-bb9f8e4e-eb0f-4097-8676-4f3dd6ec188e.png)

## Acceptance Criteria

- [ ] Display a button to edit your entry 
   - [ ] This button should only be visible on the "details" card
- [ ] Display a save button to save the changes 
- [ ] Display a cancel button to cancel the "edit mode" without saving

## Tasks

- [ ] Create a `useState` to track if the "edit mode" is toggled on or off
- [ ] Create an edit button 
   - [ ] This button toggles the "edit mode" on 
- [ ] Create a save button to save the changes and toggle the "edit mode" off 
   - [ ] Have the button trigger an onSubmit event
   - [ ] Save the changes to locale storage
   - [ ] Toggle the `useState` to turn off "edit mode"
- [ ] Create a cancel button to turn "edit mode" off
   - [ ] Create an onClick to Toggle the `useState` to turn off "edit mode"

## Complexity

L

**Comment by ghost** [comment]
again some formatting issues, but this looks well structured
