### ISSUE TITLE
change list

### ISSUE THREAD

**Issue by JohannesMisch** [JohannesMisch/Capstone-project#19]
## Value Proposition

As a Developer
I want to redo my landing page
so that I have a list of all the devices on my landing page.

## Description

![US9](https://user-images.githubusercontent.com/84077369/215882450-d66813e3-037b-4863-847d-d27292dc5459.png)

## Acceptance Criteria

- [ ] Display the list of all devices  under the chart

## Tasks

- [ ] Delete "helper list" from `add-device.js`
- [ ] Copy the list with all devices from `index.js` to `add-device.js` 
- [ ] Rename `add-device.js` to `index.js`
- [ ] Fix up all the imports that broke during the steps above (not sure what's going to break but something has to )

## Complexity

S

**Comment by anotherMichaelMaier** [comment]
Hey Johannes I'm not sure if your value proposition matches your tasks.
It sounds more like your tasks are to fix some code instead of describing the tasks you'll face.
Maybe you could try to describe more what you need to fulfill your US.
