### ISSUE TITLE
User-Story  Button Conditional Rendering

### ISSUE THREAD

**Issue by JohannesMisch** [JohannesMisch/Capstone-project#2]
## Value Proposition

As a Use
I want to have a button
so that I can press the button to see the details of this card.  

## Description

![Image](https://user-images.githubusercontent.com/84077369/213674039-1a7affe4-ffb1-4f92-a8c0-1e2875eae644.png)

## Acceptance Criteria

- [x] button with text "Details"
   - [x] if the card shows no details, click the button to render the card with details
   - [x] if the card shows details, click the button to render the card without details

## Tasks

- [x] create Button
    - [x] button needs to be able to compare the id with the id of the card
    - [x] if the button is clicked and card id = button id then render card details
    - [x] if a card shows details, render button with text: X
    - [x] if the button is clicked and card id = button id && card shows details then hide details
  
 
## Complexity
S

**Comment by Mistake91** [comment]
Hey Johannes, you could write down what details you want to render when the button is clicked, but atleast i can see it in the description :)
