### ISSUE TITLE
delete pop-up

### ISSUE THREAD

**Issue by JohannesMisch** [JohannesMisch/Capstone-project#20]
## Value Proposition

As a user 
I want to have a pop-up when I click the delete button 
so that I don't delete devices by accident

## Description

![US10](https://user-images.githubusercontent.com/84077369/215989281-4146a350-072f-4f80-91e4-1cd2e0cef94c.png)

## Acceptance Criteria
- [ ] A pop-up window should render when the user clicks on the delete button
- [ ] The delete function should only be executed when you click the "Yes" button on the pop-up window
- [ ] The delete function should be canceled when you click the "NO" button on the pop-up window

## Tasks

- [ ] Create a component `OnDeletePopUP.js `
- [ ] Create a modal (pop-up) which displays a "Yes" and a "No" button
- [ ] Remove the `handleDelete()` from the delete button 
- [ ] Give the 'Delete' button an `onClick={}` with the function to render the modal
- [ ] Inside the modal give the "Yes" button the `handleDelete()` function 
- [ ] Inside the modal give the "No" button a function to close the modal and cancel the delete process

## Complexity

L

**Comment by minatimar** [comment]
lgtm - happy hacking :)
