### ISSUE TITLE
New data input

### ISSUE THREAD

**Issue by JohannesMisch** [JohannesMisch/Capstone-project#22]
## Value Proposition

As a user
I want to have multiple buttons 
so that I can toggle between different data sets to feed the chart with different data.

## Description

![US differnt charts](https://user-images.githubusercontent.com/84077369/216296884-fbcfee7f-e27d-4771-826d-b1596ace4546.png)

## Acceptance Criteria

- [ ] Display 3 different buttons above the chart 
- [ ] `onClick` render the chart with the corresponding dataset(onClick category button displays a chart where the segments are the categories)

## Tasks

- [ ] Create three buttons "category", "location", "individual"
- [ ] Modify my existing calculations so that the calculation takes in category or location to filter the array accordingly
- [ ] Create a state to track which button was clicked 
- [ ] Create a function to provide the data for the charts 

## Complexity

L
