### ISSUE TITLE
User-Story Add new Page

### ISSUE THREAD

**Issue by JohannesMisch** [JohannesMisch/Capstone-project#4]
## Value Proposition

As a user 
I want to have a page  
where  I can add new devices.

## Description

![User Story  Add page](https://user-images.githubusercontent.com/84077369/214135208-1c0534a3-6269-4930-9064-2a0a5ab64a7a.png)

## Acceptance Criteria
- [x] add a new page 
- [x] this page contains five input fields, the user can provide data via these input fields
- [x]  this page also contains two dropdown menus where you can select device category and location

## Tasks

- [x] Create a Form component
   - [x] inside the form component create five input fields with a label for each input field
   - [x] inside the form component create two dropdown menus with a label for each menu

## Complexity

S

**Comment by minatimar** [comment]
typo in acceptance criteria... not devise...
