### ISSUE TITLE
User Story Form Button 

### ISSUE THREAD

**Issue by JohannesMisch** [JohannesMisch/Capstone-project#7]
## Value Proposition

As a user 
I want to have a button that can show or hide the add device form.

## Description
![Form button ](https://user-images.githubusercontent.com/84077369/214814834-6240aabb-bd47-4fed-9597-3c3f7582f517.png)

## Acceptance Criteria

- [ ] display one button with a + if the form is closed (hidden) 
- [ ] display the same Button but with a - if the form is open (shown)
- [ ] the + button needs open (show) the form 
- [ ] the - button needs to close (hide ) the form

## Tasks
- [ ] create a button that displays a + if the form is closed
    - [ ] that button needs to "open" the form
   
- [ ] the same button needs to display a - if the form is open
   - [ ] that button needs to "close" the form 

## Complexity

S

**Comment by niklasrammelkamp** [comment]
Nice small story
