### ISSUE TITLE
Filter option 

### ISSUE THREAD

**Issue by JohannesMisch** [JohannesMisch/Capstone-project#9]
## Value Proposition

As a User
I want to have the option to select a  filter 
so that I can see a filtered list instead of the "original" one.

## Description

![Filter](https://user-images.githubusercontent.com/84077369/215066225-0bfb379e-c9bc-4e8c-89e3-8fe0f0d14d75.png)

## Acceptance Criteria
- [ ] a select input field needs to be displayed
- [ ] a button to filter the list needs to be displayed

## Tasks

- [ ] create a select input field with multiple options 
- [ ] create a submit button to filter the list below with the selected filter option
- [ ] create a ternary operator to conditionally render either the original list with all the entries or the filtered list with only the filtered entries

## Complexity

M

**Comment by Mistake91** [comment]
Hey Johannes for me it looks good, but maybe you want to add a button to reset the filtered list so you see the original list again, maybe keep that in your mind :)

**Comment by JohannesMisch** [comment]
Hey @Mistake91 I will! great input thanks.
